[general]
static=yes
writeprotect=yes

[internal]
exten => 1001,1,NoOp(Call to extension 1001)
 same => n,Dial(PJSIP/1001,30)
 same => n,Hangup()

exten => 1002,1,NoOp(Call to extension 1002)
 same => n,Dial(PJSIP/1002,30)
 same => n,Hangup()

exten => 600,1,Answer()
 same => n,Echo()
 same => n,Hangup()

exten => 700,1,Answer()
 same => n,Playback(hello-world)
 same => n,Hangup()
