---
- name: Install required system packages
  ansible.builtin.dnf:
    name:
      - podman
      - firewalld
      - curl
      - git
      - tar
      - policycoreutils-python-utils
      - container-selinux
    state: present
